name: levelup_problems
description: A bilingual learning app where users solve problems from easiest to hardest.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/problems.json